# Exported from Render on 2024-07-18T15:48:42Z
services:
- type: web
  name: portfolio
  runtime: docker
  repo: https://github.com/sumanth321123/portfolio
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
